export const CATEGORIES = [
  { id: '1', name: 'Electronics', icon: '📱', color: '#3B82F6' },
  { id: '2', name: 'Fashion', icon: '👗', color: '#EC4899' },
  { id: '3', name: 'Home', icon: '🏠', color: '#10B981' },
  { id: '4', name: 'Sports', icon: '⚽', color: '#F59E0B' },
  { id: '5', name: 'Books', icon: '📚', color: '#8B5CF6' },
  { id: '6', name: 'Beauty', icon: '💄', color: '#F472B6' },
];

export const PRODUCTS = [
  {
    id: '1',
    name: 'Wireless Headphones Pro',
    price: '$89.99',
    originalPrice: '$129.99',
    image: '🎧',
    rating: 4.8,
    category: 'Electronics',
    discount: 31,
    isNew: false,
  },
  {
    id: '2',
    name: 'Smart Watch Series 9',
    price: '$249.99',
    originalPrice: '$299.99',
    image: '⌚',
    rating: 4.9,
    category: 'Electronics',
    discount: 17,
    isNew: true,
  },
  {
    id: '3',
    name: 'Running Shoes Elite',
    price: '$79.99',
    originalPrice: '$99.99',
    image: '👟',
    rating: 4.7,
    category: 'Sports',
    discount: 20,
    isNew: false,
  },
  {
    id: '4',
    name: 'Designer Handbag',
    price: '$199.99',
    originalPrice: '$249.99',
    image: '👜',
    rating: 4.6,
    category: 'Fashion',
    discount: 20,
    isNew: false,
  },
  {
    id: '5',
    name: 'Premium Coffee Maker',
    price: '$149.99',
    originalPrice: '$179.99',
    image: '☕',
    rating: 4.5,
    category: 'Home',
    discount: 17,
    isNew: false,
  },
  {
    id: '6',
    name: 'Yoga Mat Pro',
    price: '$34.99',
    originalPrice: '$49.99',
    image: '🧘',
    rating: 4.8,
    category: 'Sports',
    discount: 30,
    isNew: false,
  },
  {
    id: '7',
    name: 'Laptop Ultra',
    price: '$899.99',
    originalPrice: '$1199.99',
    image: '💻',
    rating: 4.9,
    category: 'Electronics',
    discount: 25,
    isNew: true,
  },
  {
    id: '8',
    name: 'Sunglasses Classic',
    price: '$59.99',
    originalPrice: '$79.99',
    image: '🕶️',
    rating: 4.7,
    category: 'Fashion',
    discount: 25,
    isNew: false,
  },
];
