import { StyleSheet, Dimensions } from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
const PRODUCT_CARD_WIDTH = (SCREEN_WIDTH - 48) / 2;

export const useStyles = (isDark: boolean) => {
  const colors = {
    background: isDark ? '#0F172A' : '#FFFFFF',
    surface: isDark ? '#1E293B' : '#F8FAFC',
    text: isDark ? '#F1F5F9' : '#0F172A',
    textSecondary: isDark ? '#94A3B8' : '#64748B',
    primary: isDark ? '#60A5FA' : '#3B82F6',
    border: isDark ? '#334155' : '#E2E8F0',
    card: isDark ? '#1E293B' : '#FFFFFF',
    accent: isDark ? '#34D399' : '#10B981',
  };

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scrollView: {
      flex: 1,
    },
    scrollContent: {
      paddingBottom: 24,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      paddingHorizontal: 20,
      paddingTop: 16,
      paddingBottom: 20,
    },
    headerLeft: {
      flex: 1,
    },
    greeting: {
      fontSize: 16,
      color: colors.textSecondary,
      marginBottom: 4,
      fontWeight: '500',
    },
    headerTitle: {
      fontSize: 28,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 8,
    },
    locationContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 4,
    },
    locationIcon: {
      fontSize: 14,
      marginRight: 6,
    },
    locationText: {
      fontSize: 13,
      color: colors.textSecondary,
      fontWeight: '500',
    },
    cartButton: {
      position: 'relative',
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    cartIcon: {
      fontSize: 20,
    },
    cartBadge: {
      position: 'absolute',
      top: -2,
      right: -2,
      backgroundColor: '#EF4444',
      borderRadius: 10,
      minWidth: 20,
      height: 20,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 4,
    },
    cartBadgeText: {
      color: '#FFFFFF',
      fontSize: 11,
      fontWeight: '700',
    },
    searchBar: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surface,
      marginHorizontal: 20,
      marginBottom: 20,
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    searchIcon: {
      fontSize: 18,
      marginRight: 12,
    },
    searchPlaceholder: {
      fontSize: 15,
      color: colors.textSecondary,
      flex: 1,
    },
    filterButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      marginLeft: 8,
    },
    filterIcon: {
      fontSize: 14,
    },
    section: {
      marginBottom: 32,
    },
    promoBanner: {
      marginHorizontal: 20,
      marginBottom: 24,
      backgroundColor: colors.primary,
      borderRadius: 20,
      padding: 20,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
      elevation: 8,
    },
    promoContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    promoLeft: {
      flex: 1,
    },
    promoTitle: {
      fontSize: 22,
      fontWeight: '700',
      color: '#FFFFFF',
      marginBottom: 4,
    },
    promoSubtitle: {
      fontSize: 14,
      color: '#FFFFFF',
      opacity: 0.9,
      fontWeight: '500',
    },
    promoRight: {
      width: 60,
      height: 60,
      borderRadius: 30,
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    promoEmoji: {
      fontSize: 32,
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      marginBottom: 16,
    },
    sectionTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: colors.text,
    },
    seeAllText: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.primary,
    },
    categoriesContainer: {
      paddingHorizontal: 20,
      gap: 12,
    },
    categoryCard: {
      width: 100,
      paddingVertical: 20,
      paddingHorizontal: 16,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    categoryIcon: {
      fontSize: 32,
      marginBottom: 8,
    },
    categoryName: {
      fontSize: 13,
      fontWeight: '600',
      color: '#FFFFFF',
      textAlign: 'center',
    },
    productsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      paddingHorizontal: 20,
      gap: 12,
    },
    productsRow: {
      paddingHorizontal: 20,
      gap: 12,
      marginBottom: 12,
    },
    productCard: {
      width: PRODUCT_CARD_WIDTH,
      backgroundColor: colors.card,
      borderRadius: 18,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 4,
    },
    productImageContainer: {
      width: '100%',
      height: 150,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
    },
    productImage: {
      fontSize: 70,
    },
    newBadge: {
      position: 'absolute',
      top: 8,
      left: 8,
      backgroundColor: '#10B981',
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 6,
    },
    newBadgeText: {
      color: '#FFFFFF',
      fontSize: 10,
      fontWeight: '700',
      letterSpacing: 0.5,
    },
    discountBadge: {
      position: 'absolute',
      top: 8,
      left: 8,
      backgroundColor: '#EF4444',
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 6,
    },
    discountBadgeText: {
      color: '#FFFFFF',
      fontSize: 11,
      fontWeight: '700',
    },
    ratingBadge: {
      position: 'absolute',
      top: 8,
      right: 8,
      backgroundColor: 'rgba(0, 0, 0, 0.65)',
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 8,
      flexDirection: 'row',
      alignItems: 'center',
    },
    ratingText: {
      color: '#FFFFFF',
      fontSize: 11,
      fontWeight: '600',
    },
    productInfo: {
      padding: 12,
    },
    productName: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.text,
      marginBottom: 8,
      minHeight: 36,
    },
    priceContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    productPrice: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.accent,
    },
    originalPrice: {
      fontSize: 13,
      color: colors.textSecondary,
      textDecorationLine: 'line-through',
    },
    offerBanner: {
      marginHorizontal: 20,
      backgroundColor: colors.primary,
      borderRadius: 24,
      padding: 24,
      overflow: 'hidden',
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.3,
      shadowRadius: 16,
      elevation: 10,
    },
    offerContent: {
      alignItems: 'center',
    },
    offerEmoji: {
      fontSize: 48,
      marginBottom: 12,
    },
    offerTitle: {
      fontSize: 26,
      fontWeight: '700',
      color: '#FFFFFF',
      marginBottom: 8,
      textAlign: 'center',
    },
    offerSubtitle: {
      fontSize: 15,
      color: '#FFFFFF',
      opacity: 0.95,
      marginBottom: 20,
      textAlign: 'center',
      lineHeight: 22,
    },
    offerButton: {
      backgroundColor: '#FFFFFF',
      paddingHorizontal: 24,
      paddingVertical: 14,
      borderRadius: 14,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    offerButtonText: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.primary,
    },
    offerButtonArrow: {
      fontSize: 18,
      color: colors.primary,
      fontWeight: '700',
    },
  });
};

