import { StyleSheet } from 'react-native';

export const makeStyles = (width: number, height: number) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#0F0B1F',
      position: 'relative',
    },
    decorativeCircle1: {
      position: 'absolute',
      width: width * 1.2,
      height: width * 1.2,
      borderRadius: width * 0.6,
      backgroundColor: 'rgba(139, 69, 139, 0.15)',
      top: -width * 0.4,
      left: -width * 0.3,
    },
    decorativeCircle2: {
      position: 'absolute',
      width: width * 0.8,
      height: width * 0.8,
      borderRadius: width * 0.4,
      backgroundColor: 'rgba(75, 0, 130, 0.2)',
      top: height * 0.15,
      right: -width * 0.4,
    },
    decorativeCircle3: {
      position: 'absolute',
      width: width * 1.5,
      height: width * 1.5,
      borderRadius: width * 0.75,
      backgroundColor: 'rgba(25, 15, 45, 0.8)',
      bottom: -width * 0.5,
      left: -width * 0.2,
    },
    content: {
      flex: 1,
      paddingHorizontal: 40,
      justifyContent: 'center',
      zIndex: 1,
    },
    logoContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 20,
    },
    lottieAnimation: {
      width: width * 0.5,
      height: height * 0.2,
    },
    ethereumLogo: {
      width: 120,
      height: 140,
      alignItems: 'center',
      justifyContent: 'center',
    },
    ethereumTop: {
      width: 0,
      height: 0,
      backgroundColor: 'transparent',
      borderStyle: 'solid',
      borderLeftWidth: 40,
      borderRightWidth: 40,
      borderBottomWidth: 70,
      borderLeftColor: 'transparent',
      borderRightColor: 'transparent',
      borderBottomColor: '#C96B98',
      marginBottom: -5,
    },
    ethereumBottom: {
      width: 0,
      height: 0,
      backgroundColor: 'transparent',
      borderStyle: 'solid',
      borderLeftWidth: 40,
      borderRightWidth: 40,
      borderTopWidth: 70,
      borderLeftColor: 'transparent',
      borderRightColor: 'transparent',
      borderTopColor: '#E89BB5',
    },
    title: {
      fontSize: 42,
      fontWeight: 'bold',
      color: '#FFFFFF',
      textAlign: 'center',
      marginBottom: 8,
      letterSpacing: 1,
    },
    subtitle: {
      fontSize: 14,
      color: '#A89FC6',
      textAlign: 'center',
      marginBottom: 50,
    },
    inputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(255, 255, 255, 0.05)',
      borderWidth: 1.5,
      borderColor: '#8B4789',
      borderRadius: 25,
      paddingHorizontal: 20,
      paddingVertical: 15,
      marginBottom: 20,
    },
    inputIcon: {
      marginRight: 12,
    },
    input: {
      flex: 1,
      color: '#FFFFFF',
      fontSize: 16,
    },
    eyeButton: {
      padding: 5,
    },
    eyeIcon: {
      fontSize: 18,
      color: '#A89FC6',
    },
    loginButton: {
      borderRadius: 25,
      overflow: 'hidden',
      marginTop: 10,
      marginBottom: 25,
    },
    gradientButton: {
      paddingVertical: 18,
      justifyContent: 'center',
      width: '100%',
      borderRadius: 8,
    },
    loginButtonText: {
      color: '#FFFFFF',
      fontSize: 18,
      fontWeight: '600',
      textAlign: 'center',
      marginBottom: 30,
    },
    linksContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 60,
    },
    linkText: {
      color: '#E89BB5',
      fontSize: 14,
      fontWeight: '500',
    },
    metamaskButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: '#E89BB5',
      borderRadius: 25,
      paddingVertical: 16,
      gap: 10,
    },
    metamaskText: {
      color: '#E89BB5',
      fontSize: 16,
      fontWeight: '600',
    },
    metamaskIcon: {
      fontSize: 24,
    },
  });
