import { StyleSheet, Dimensions } from 'react-native';

const { height: SCREEN_HEIGHT } = Dimensions.get('window');

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.2,
    shadowRadius: 24,
    elevation: 24,
    overflow: 'hidden',
    height: SCREEN_HEIGHT * 0.75,
    maxHeight: SCREEN_HEIGHT * 0.95,
  },
  modalHandleContainer: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  modalHandle: {
    width: 48,
    height: 5,
    backgroundColor: '#9CA3AF',
    borderRadius: 3,
  },
  modalHeader: {
    position: 'relative',
    height: 50,
    justifyContent: 'center',
    alignItems: 'flex-end',
    paddingRight: 16,
    paddingTop: 4,
  },
  modalCloseButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  iconContainer: {
    marginBottom: 8,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  prePermissionContainer: {
    backgroundColor: '#FFFFFF',
    flex: 1,
    minHeight: 400,
  },
  prePermissionContent: {
    padding: 24,
    paddingTop: 8,
    paddingBottom: 40,
    flexGrow: 1,
  },
  prePermissionHeader: {
    alignItems: 'center',
    marginBottom: 40,
    paddingTop: 8,
  },
  iconWrapper: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#ECFDF5',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
    borderWidth: 2,
    borderColor: '#D1FAE5',
  },
  prePermissionIcon: {
    // Icon styles
  },
  prePermissionTitle: {
    fontSize: 32,
    fontWeight: '800',
    color: '#111827',
    textAlign: 'center',
    letterSpacing: -0.5,
    marginBottom: 8,
  },
  prePermissionSubtitle: {
    fontSize: 16,
    color: '#6B7280',
    textAlign: 'center',
    fontWeight: '500',
    letterSpacing: 0.2,
  },
  prePermissionBody: {
    marginBottom: 40,
  },
  prePermissionDescription: {
    fontSize: 17,
    lineHeight: 28,
    color: '#374151',
    marginBottom: 32,
    letterSpacing: 0.1,
    textAlign: 'center',
    fontWeight: '500',
  },
  prePermissionSection: {
    marginBottom: 20,
    backgroundColor: '#F9FAFB',
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionIconContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#D1FAE5',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  prePermissionSectionTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#111827',
    letterSpacing: 0.1,
    flex: 1,
  },
  prePermissionSectionText: {
    fontSize: 15,
    lineHeight: 24,
    color: '#4B5563',
    letterSpacing: 0.05,
    fontWeight: '400',
    paddingLeft: 44,
  },
  alternativeItem: {
    flexDirection: 'row',
    marginTop: 8,
    paddingLeft: 44,
  },
  alternativeBullet: {
    fontSize: 16,
    color: '#6366F1',
    marginRight: 8,
    fontWeight: '600',
  },
  prePermissionAlternative: {
    fontSize: 15,
    lineHeight: 24,
    color: '#4B5563',
    letterSpacing: 0.05,
    fontWeight: '400',
    flex: 1,
  },
  prePermissionActions: {
    gap: 12,
    paddingBottom: 20,
  },
  prePermissionButtonPrimary: {
    backgroundColor: '#10B981',
    borderRadius: 16,
    paddingVertical: 18,
    paddingHorizontal: 32,
    alignItems: 'center',
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 4,
    marginBottom: 12,
  },
  prePermissionButtonPrimaryText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  prePermissionButtonSecondary: {
    backgroundColor: 'transparent',
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 32,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
  },
  prePermissionButtonSecondaryText: {
    color: '#6B7280',
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  prePermissionButtonDisabled: {
    opacity: 0.6,
  },

  statusCard: {
    borderRadius: 20,
    padding: 24,
    marginBottom: 16,
    borderWidth: 1,
    overflow: 'hidden',
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  statusCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  statusCardIcon: {
    marginRight: 16,
  },
  statusCardInfo: {
    flex: 1,
  },
  statusCardName: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1A1A1A',
    marginBottom: 6,
    letterSpacing: 0.2,
  },
  statusCardStatusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  statusCardStatusIcon: {
    marginRight: 2,
  },
  statusCardStatus: {
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  statusCardActions: {
    marginTop: 4,
  },
  statusCardAction: {
    paddingVertical: 10,
  },
  statusCardActionText: {
    fontSize: 14,
    color: '#6B7280',
    letterSpacing: 0.2,
  },
  statusCardButton: {
    backgroundColor: '#F3F4F6',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  statusCardButtonText: {
    color: '#1A1A1A',
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0.2,
  },

  statusGranted: {
    color: '#10B981',
  },
  statusGrantedBg: {
    backgroundColor: '#F0FDF4',
    borderColor: '#D1FAE5',
  },
  statusDenied: {
    color: '#F59E0B',
  },
  statusDeniedBg: {
    backgroundColor: '#FFFBEB',
    borderColor: '#FEF3C7',
  },
  statusBlocked: {
    color: '#EF4444',
  },
  statusBlockedBg: {
    backgroundColor: '#FEF2F2',
    borderColor: '#FEE2E2',
  },
  statusUnknown: {
    color: '#6B7280',
  },
  statusUnknownBg: {
    backgroundColor: '#F9FAFB',
    borderColor: '#E5E7EB',
  },
});
